site_name: NB.MATHS
site_url: https://s-roll.github.io/notebook.maths/
site_author: Bang Nguyen

nav:
  - Home: index.md
  - Maths:
    - maths/index.md
    #- Measure theory: maths/measuretheory.md
    - Giải tích hàm:
      - maths/GTH/index.md
      - Không gian metric: maths/GTH/metric.md
    - Lý thuyết mật mã: maths/cryptography.md
    - Cấu trúc rời rạc: maths/discrete.md
    # - Statistics: maths/statistics.md
    - Giải tích số: maths/numericalmethods.md
    - Phương trình vi phân: maths/ode.md
    - Giải tích phức: maths/complexanalysis.md
    # - Differential equation:
    #- Machine learning: maths/machinelearning.md
  - Computer:
    - Data structure & Algorithm: computer/dsa.md
    - Languages:
      - Python: computer/python/python.md
      - C++: computer/cpp/cpp.md
    - Technique: 
      - Python package: computer/python/py-package.md
      - Venv setting: computer/python/py-up.md
      - Mkdocs setting: computer/mkdocs/mkdocs.md
      - Other: computer/other/other.md
      #- Open source: computer/opensource.md
    - Algorithms:
      - Ranking: computer/algorithms/ranking.md

plugins:
    - search: {}
    - encryptcontent:
        title_prefix: ''
        summary: 'Bạn cần có password để vào được trang này.'
        placeholder: 'Nhập password'
        decryption_failure_message: 'Try again!'
        encryption_info_message: "Vui lòng nhập password vào bên dưới"
        input_class: 'md-search__form md-search__input'
        button_class: 'md-search__icon'


theme:
  name: material
  features:
     - toc.follow
     - navigation.footer
     - navigation.tabs
     - navigation.tabs.sticky
     - navigation.expand
     - navigation.path
     - navigation.indexes
     - navigation.instant.preview
     - navigation.sections
     - navigation.top
     - search.suggest
     - search.highlight
     - content.tabs.link
     - content.code.annotation
     - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/weather-night
        name: Switch to light mode    
      primary: teal
      accent: lime
  font:
    text: Open Sans
  logo: bancie.png
  favicon: bancie.png
  icon:
    logo: logo
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  

extra_javascript:
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css
  - stylesheets/extra.css

copyright: |
  &copy; 2024 <a href="https://web.facebook.com/ngchibangg"  target="_blank" rel="noopener">Bang Nguyen</a>

extra:
  homepage: https://s-roll.github.io/notebook.maths/
  social:
    - icon: fontawesome/brands/facebook
      link: https://web.facebook.com/ngchibangg
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/bancie.007/